[workspace]
resolver = "2"
members = [
  "apps/backend",
  "apps/site-runtime",
  "crates/domain",
  "crates/executor-core",
  "crates/shared",
]

[workspace.package]
edition = "2021"
license = "MIT"
repository = "https://github.com/gabriell211/Seven-Network-Manager"
rust-version = "1.81"

[workspace.dependencies]
anyhow = "1"
async-trait = "0.1"
axum = "0.7"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal"] }
tower-http = { version = "0.6", features = ["cors", "trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
uuid = { version = "1", features = ["serde", "v4"] }
