#!/usr/bin/env python3
from __future__ import annotations

import argparse
import copy
import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SPEC = ROOT / "apps/frontend/public/openapi-v1.json"
FRAGMENTS = ROOT / "contracts/openapi"
OUTPUT = ROOT / "apps/frontend/src/generated/api-contract.ts"


def ts_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "anyOf" in schema:
        return " | ".join(ts_type(item) for item in schema["anyOf"])
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])

    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        return " | ".join(
            "null" if item == "null" else ts_type({**schema, "type": item})
            for item in schema_type
        )
    if schema_type == "string":
        return "string"
    if schema_type in {"integer", "number"}:
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "null":
        return "null"
    if schema_type == "array":
        return f"Array<{ts_type(schema.get('items', {}))}>"
    if schema_type == "object":
        properties = schema.get("properties", {})
        required = set(schema.get("required", []))
        if not properties:
            return "Record<string, unknown>"
        body = "; ".join(
            f"{name}{'' if name in required else '?'}: {ts_type(value)}"
            for name, value in properties.items()
        )
        return "{ " + body + " }"
    return "unknown"


def merge_contract(base: dict[str, Any]) -> dict[str, Any]:
    merged = copy.deepcopy(base)
    merged.setdefault("paths", {})
    components = merged.setdefault("components", {})
    schemas = components.setdefault("schemas", {})

    if not FRAGMENTS.exists():
        return merged

    for fragment_path in sorted(FRAGMENTS.glob("*.json")):
        fragment = json.loads(fragment_path.read_text(encoding="utf-8"))
        for path, definition in fragment.get("paths", {}).items():
            merged["paths"][path] = definition
        for name, definition in fragment.get("schemas", {}).items():
            schemas[name] = definition
    return merged


def generate(spec: dict[str, Any]) -> str:
    schemas = spec["components"]["schemas"]
    lines = [
        "// Generated by scripts/generate_frontend_contract.py. Do not edit manually.",
        "// Sources: apps/frontend/public/openapi-v1.json + contracts/openapi/*.json",
        "",
    ]
    for name in sorted(schemas):
        schema = schemas[name]
        if schema.get("type") == "object" and "properties" in schema:
            required = set(schema.get("required", []))
            lines.append(f"export interface {name} {{")
            for field, field_schema in schema["properties"].items():
                optional = "" if field in required else "?"
                lines.append(f"  {field}{optional}: {ts_type(field_schema)};")
            lines.append("}")
        else:
            lines.append(f"export type {name} = {ts_type(schema)};")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    persisted = json.loads(SPEC.read_text(encoding="utf-8"))
    merged = merge_contract(persisted)
    generated = generate(merged)
    serialized = json.dumps(merged, ensure_ascii=False, indent=2) + "\n"

    if args.check:
        problems: list[str] = []
        if SPEC.read_text(encoding="utf-8") != serialized:
            problems.append("versioned OpenAPI document is stale")
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != generated:
            problems.append("frontend TypeScript contract is stale")
        if problems:
            print("; ".join(problems) + "; run scripts/generate_frontend_contract.py")
            return 1
        print("OpenAPI document and frontend contract are up to date")
        return 0

    SPEC.write_text(serialized, encoding="utf-8")
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(generated, encoding="utf-8")
    print(f"wrote {SPEC.relative_to(ROOT)}")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
