#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SPEC = ROOT / "apps/frontend/public/openapi-v1.json"
OUTPUT = ROOT / "apps/frontend/src/generated/api-contract.ts"


def ts_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "anyOf" in schema:
        return " | ".join(ts_type(item) for item in schema["anyOf"])
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])

    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        return " | ".join(
            "null" if item == "null" else ts_type({**schema, "type": item})
            for item in schema_type
        )
    if schema_type == "string":
        return "string"
    if schema_type in {"integer", "number"}:
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "null":
        return "null"
    if schema_type == "array":
        return f"Array<{ts_type(schema.get('items', {}))}>"
    if schema_type == "object":
        properties = schema.get("properties", {})
        required = set(schema.get("required", []))
        if not properties:
            return "Record<string, unknown>"
        body = "; ".join(
            f"{name}{'' if name in required else '?'}: {ts_type(value)}"
            for name, value in properties.items()
        )
        return "{ " + body + " }"
    return "unknown"


def generate(spec: dict[str, Any]) -> str:
    schemas = spec["components"]["schemas"]
    lines = [
        "// Generated by scripts/generate_frontend_contract.py. Do not edit manually.",
        "// Source: apps/frontend/public/openapi-v1.json",
        "",
    ]
    for name in sorted(schemas):
        schema = schemas[name]
        if schema.get("type") == "object" and "properties" in schema:
            required = set(schema.get("required", []))
            lines.append(f"export interface {name} {{")
            for field, field_schema in schema["properties"].items():
                optional = "" if field in required else "?"
                lines.append(f"  {field}{optional}: {ts_type(field_schema)};")
            lines.append("}")
        else:
            lines.append(f"export type {name} = {ts_type(schema)};")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    spec = json.loads(SPEC.read_text(encoding="utf-8"))
    generated = generate(spec)
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != generated:
            print("frontend contract is stale; run scripts/generate_frontend_contract.py")
            return 1
        print("frontend contract is up to date")
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(generated, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
